services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rmshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: 
      context: ./rmshop-auth-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rmshop
      - JWT_SECRET=your-secret-key
      - SERVER_PORT=50051
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 